# Generated by Django 4.2.16 on 2024-10-27 11:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ammonia',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 27, 11, 27, 43, 611854, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='bod',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 27, 11, 27, 43, 611553, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='dissolvedoxygen',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 27, 11, 27, 43, 611708, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='fecaluniform',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 27, 11, 27, 43, 612340, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='inorganicphospate',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 27, 11, 27, 43, 612143, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='nitrate',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 27, 11, 27, 43, 611998, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='ph',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 27, 11, 27, 43, 611164, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='temperature',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 27, 11, 27, 43, 612627, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='turbidity',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 27, 11, 27, 43, 612484, tzinfo=datetime.timezone.utc)),
        ),
    ]
