# Generated by Django 4.2.16 on 2024-10-27 11:34

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_ammonia_time_alter_bod_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ammonia',
            name='time',
            field=models.DateTimeField(default=api.models.Ammonia.getTime),
        ),
        migrations.AlterField(
            model_name='bod',
            name='time',
            field=models.DateTimeField(default=api.models.BOD.getTime),
        ),
        migrations.AlterField(
            model_name='dissolvedoxygen',
            name='time',
            field=models.DateTimeField(default=api.models.DissolvedOxygen.getTime),
        ),
        migrations.AlterField(
            model_name='fecaluniform',
            name='time',
            field=models.DateTimeField(default=api.models.FecalUniform.getTime),
        ),
        migrations.AlterField(
            model_name='inorganicphospate',
            name='time',
            field=models.DateTimeField(default=api.models.InorganicPhospate.getTime),
        ),
        migrations.AlterField(
            model_name='nitrate',
            name='time',
            field=models.DateTimeField(default=api.models.Nitrate.getTime),
        ),
        migrations.AlterField(
            model_name='ph',
            name='time',
            field=models.DateTimeField(default=api.models.pH.getTime),
        ),
        migrations.AlterField(
            model_name='temperature',
            name='time',
            field=models.DateTimeField(default=api.models.Temperature.getTime),
        ),
        migrations.AlterField(
            model_name='turbidity',
            name='time',
            field=models.DateTimeField(default=api.models.Turbidity.getTime),
        ),
    ]
