# Generated by Django 4.2.16 on 2024-11-18 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_tds'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='fecaluniform',
            table='fecalcoliform',
        ),
    ]
