# Generated by Django 4.2.16 on 2024-11-18 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_fecaluniform_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='fecaluniform',
            table='api_fecalcoliform',
        ),
    ]
