# Generated by Django 4.2.16 on 2025-04-24 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_orp'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='ammonia',
            index=models.Index(fields=['station', '-time'], name='api_ammonia_station_50711d_idx'),
        ),
        migrations.AddIndex(
            model_name='bod',
            index=models.Index(fields=['station', '-time'], name='api_bod_station_a3df61_idx'),
        ),
        migrations.AddIndex(
            model_name='dissolvedoxygen',
            index=models.Index(fields=['station', '-time'], name='api_dissolv_station_a4e610_idx'),
        ),
        migrations.AddIndex(
            model_name='fecaluniform',
            index=models.Index(fields=['station', '-time'], name='api_fecalun_station_8ededb_idx'),
        ),
        migrations.AddIndex(
            model_name='inorganicphospate',
            index=models.Index(fields=['station', '-time'], name='api_inorgan_station_38e727_idx'),
        ),
        migrations.AddIndex(
            model_name='nitrate',
            index=models.Index(fields=['station', '-time'], name='api_nitrate_station_ea1bdb_idx'),
        ),
        migrations.AddIndex(
            model_name='orp',
            index=models.Index(fields=['station', '-time'], name='api_orp_station_61f59a_idx'),
        ),
        migrations.AddIndex(
            model_name='ph',
            index=models.Index(fields=['station', '-time'], name='api_ph_station_a91698_idx'),
        ),
        migrations.AddIndex(
            model_name='tds',
            index=models.Index(fields=['station', '-time'], name='api_tds_station_63adf3_idx'),
        ),
        migrations.AddIndex(
            model_name='temperature',
            index=models.Index(fields=['station', '-time'], name='api_tempera_station_b25599_idx'),
        ),
        migrations.AddIndex(
            model_name='turbidity',
            index=models.Index(fields=['station', '-time'], name='api_turbidi_station_860b42_idx'),
        ),
        migrations.AlterModelTable(
            name='fecaluniform',
            table=None,
        ),
    ]
