# Generated by Django 4.2.16 on 2025-05-17 10:33

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_ammonia_api_ammonia_station_50711d_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DimSensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('unit', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DimStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DimTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ReportLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('success', models.BooleanField(default=True)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='SensorAlertLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('classification', models.CharField(max_length=20)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.dimsensor')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.dimstation')),
            ],
        ),
        migrations.CreateModel(
            name='RawSensorReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('value', models.FloatField()),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.dimsensor')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.dimstation')),
            ],
            options={
                'indexes': [models.Index(fields=['station', 'sensor', 'timestamp'], name='api_rawsens_station_df20e7_idx'), models.Index(fields=['timestamp'], name='api_rawsens_timesta_2071ba_idx')],
            },
        ),
        migrations.CreateModel(
            name='FactSensorReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.dimsensor')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.dimstation')),
                ('time', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.dimtime')),
            ],
            options={
                'indexes': [models.Index(fields=['station', 'sensor', 'time'], name='api_factsen_station_001e93_idx')],
                'unique_together': {('station', 'sensor', 'time')},
            },
        ),
    ]
