# Generated by Django 4.2.16 on 2025-05-17 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_dimsensor_dimstation_dimtime_reportlog_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='dimsensor',
            index=models.Index(fields=['name'], name='api_dimsens_name_d0ad4d_idx'),
        ),
        migrations.AddIndex(
            model_name='dimstation',
            index=models.Index(fields=['code'], name='api_dimstat_code_9cdaab_idx'),
        ),
        migrations.AddIndex(
            model_name='dimtime',
            index=models.Index(fields=['date'], name='api_dimtime_date_30d910_idx'),
        ),
        migrations.AddIndex(
            model_name='factsensorreading',
            index=models.Index(fields=['station'], name='api_factsen_station_ea02c3_idx'),
        ),
        migrations.AddIndex(
            model_name='factsensorreading',
            index=models.Index(fields=['sensor'], name='api_factsen_sensor__b03a0c_idx'),
        ),
        migrations.AddIndex(
            model_name='factsensorreading',
            index=models.Index(fields=['time'], name='api_factsen_time_id_d24917_idx'),
        ),
        migrations.AddIndex(
            model_name='rawsensorreading',
            index=models.Index(fields=['station'], name='api_rawsens_station_26a9b8_idx'),
        ),
        migrations.AddIndex(
            model_name='rawsensorreading',
            index=models.Index(fields=['sensor'], name='api_rawsens_sensor__2d6cf6_idx'),
        ),
        migrations.AddIndex(
            model_name='reportlog',
            index=models.Index(fields=['timestamp'], name='api_reportl_timesta_742283_idx'),
        ),
        migrations.AddIndex(
            model_name='reportlog',
            index=models.Index(fields=['success'], name='api_reportl_success_9597e6_idx'),
        ),
        migrations.AddIndex(
            model_name='sensoralertlog',
            index=models.Index(fields=['station'], name='api_sensora_station_1571d4_idx'),
        ),
        migrations.AddIndex(
            model_name='sensoralertlog',
            index=models.Index(fields=['sensor'], name='api_sensora_sensor__444f5e_idx'),
        ),
        migrations.AddIndex(
            model_name='sensoralertlog',
            index=models.Index(fields=['timestamp'], name='api_sensora_timesta_3e84ef_idx'),
        ),
        migrations.AddIndex(
            model_name='sensoralertlog',
            index=models.Index(fields=['station', 'sensor', 'timestamp'], name='api_sensora_station_909d89_idx'),
        ),
    ]
