# Generated by Django 4.2.16 on 2025-05-18 14:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_dimsensor_api_dimsens_name_d0ad4d_idx_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sensoralertlog',
            name='classification',
        ),
        migrations.RemoveField(
            model_name='sensoralertlog',
            name='value',
        ),
        migrations.AddField(
            model_name='sensoralertlog',
            name='description',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
