# Generated by Django 4.2.16 on 2025-05-18 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_remove_sensoralertlog_classification_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportlog',
            name='type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
