# Generated by Django 4.2.16 on 2025-05-19 10:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_reportlog_type'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='reportlog',
            name='api_reportl_success_9597e6_idx',
        ),
        migrations.RemoveIndex(
            model_name='sensoralertlog',
            name='api_sensora_timesta_3e84ef_idx',
        ),
        migrations.AddField(
            model_name='reportlog',
            name='alert',
            field=models.BooleanField(default=False, help_text='True if the row represents an error / alarm situation'),
        ),
        migrations.AddField(
            model_name='sensoralertlog',
            name='alert',
            field=models.BooleanField(default=False, help_text='True if the row represents an error / alarm situation'),
        ),
        migrations.AddField(
            model_name='sensoralertlog',
            name='value',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reportlog',
            name='success',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='reportlog',
            name='timestamp',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='sensoralertlog',
            name='timestamp',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
    ]
