# Generated by Django 4.2.16 on 2025-05-20 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_remove_reportlog_api_reportl_success_9597e6_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rawsensorreading',
            name='value',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
