# Generated by Django 4.2.16 on 2025-06-09 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_rawsensorreading_value'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeeklySensorReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.dimsensor')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.dimstation')),
                ('time', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.dimtime')),
            ],
            options={
                'indexes': [models.Index(fields=['station'], name='api_weeklys_station_391615_idx'), models.Index(fields=['sensor'], name='api_weeklys_sensor__d932c8_idx'), models.Index(fields=['time'], name='api_weeklys_time_id_cdf1b5_idx'), models.Index(fields=['station', 'sensor', 'time'], name='api_weeklys_station_0c7544_idx')],
                'unique_together': {('station', 'sensor', 'time')},
            },
        ),
    ]
