# Generated by Django 4.2.16 on 2025-06-10 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_weeklysensorreading'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='rawsensorreading',
            name='api_rawsens_station_df20e7_idx',
        ),
        migrations.RemoveIndex(
            model_name='rawsensorreading',
            name='api_rawsens_timesta_2071ba_idx',
        ),
        migrations.RenameField(
            model_name='rawsensorreading',
            old_name='timestamp',
            new_name='time',
        ),
        migrations.AddIndex(
            model_name='rawsensorreading',
            index=models.Index(fields=['time'], name='api_rawsens_time_a35e3d_idx'),
        ),
        migrations.AddIndex(
            model_name='rawsensorreading',
            index=models.Index(fields=['station', 'sensor', 'time'], name='api_rawsens_station_daa26e_idx'),
        ),
    ]
