# Generated by Django 4.2.16 on 2025-06-11 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_remove_rawsensorreading_api_rawsens_station_df20e7_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailySensorReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.dimsensor')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.dimstation')),
                ('time', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.dimtime')),
            ],
            options={
                'indexes': [models.Index(fields=['station'], name='api_dailyse_station_eea211_idx'), models.Index(fields=['sensor'], name='api_dailyse_sensor__e73fdb_idx'), models.Index(fields=['time'], name='api_dailyse_time_id_5d5ba9_idx'), models.Index(fields=['station', 'sensor', 'time'], name='api_dailyse_station_afeed1_idx')],
                'unique_together': {('station', 'sensor', 'time')},
            },
        ),
    ]
