# Generated by Django 4.2.16 on 2025-04-29 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='quarter',
            field=models.CharField(default=1, max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='report',
            name='year',
            field=models.CharField(default=0, max_length=4),
            preserve_default=False,
        ),
    ]
