def get_legends():
    return {
        "pH": [
            {"color": "#4CAF50", "label": "Conformed with WQG for Classes A and B", "desc": "6.5–8.5", "unit": "units"},
            {"color": "#FFEB3B", "label": "Conformed with WQG for Class C", "desc": "6.5–9.0", "unit": "units"},
            {"color": "#FF9800", "label": "Conformed with WQG for Class D", "desc": "6.0–9.0", "unit": "units"},
            {"color": "#F44336", "label": "Failed the WQG for Classes A to D", "desc": "< 6.0 or > 9.0", "unit": "units"},
            {"color": "black", "label": "No Data", "desc": "", "unit": "units"},
        ],
        "Temperature": [
            {"color": "#4CAF50", "label": "Conformed with WQG for Classes AA-C", "desc": "26–30", "unit": "°C"},
            {"color": "#FF9800", "label": "Conformed with WQG for Class D", "desc": "25–31", "unit": "°C"},
            {"color": "#F44336", "label": "Failed the WQG for Classes AA to D", "desc": "< 25 or > 31", "unit": "°C"},
            {"color": "black", "label": "No Data", "desc": "", "unit": "°C"},
        ],
        "DO": [
            {"color": "#4CAF50", "label": "Conformed with WQG for Classes AA-C", "desc": "≥ 5", "unit": "mg/L"},
            {"color": "#FF9800", "label": "Conformed with WQG for Class D", "desc": "2–5", "unit": "mg/L"},
            {"color": "#F44336", "label": "Failed the WQG for Classes AA to D", "desc": "< 2", "unit": "mg/L"},
            {"color": "black", "label": "No Data", "desc": "", "unit": "mg/L"},
        ],
        "Turbidity": [
            {"color": "#4CAF50", "label": "Conformed with WQG for Classes AA-B", "desc": "≤ 5", "unit": "NTU"},
            {"color": "#FFEB3B", "label": "Conformed with WQG for Class C", "desc": "> 5–10", "unit": "NTU"},
            {"color": "#FF9800", "label": "Conformed with WQG for Class D", "desc": "> 10–15", "unit": "NTU"},
            {"color": "#F44336", "label": "Failed the WQG for Classes AA to D", "desc": "> 15", "unit": "NTU"},
            {"color": "black", "label": "No Data", "desc": "", "unit": "NTU"},
        ],
        "TDS": [
            {"color": "#4CAF50", "label": "Conformed with WQG for Classes AA-B", "desc": "≤ 500", "unit": "mg/L"},
            {"color": "#FFEB3B", "label": "Conformed with WQG for Class C", "desc": "> 500–1000", "unit": "mg/L"},
            {"color": "#FF9800", "label": "Conformed with WQG for Class D", "desc": "> 1000–1500", "unit": "mg/L"},
            {"color": "#F44336", "label": "Failed the WQG for Classes AA to D", "desc": "> 1500", "unit": "mg/L"},
            {"color": "black", "label": "No Data", "desc": "", "unit": "mg/L"},
        ],
        "ORP": [
            {"color": "#4CAF50", "label": "Conformed with WQG for Classes AA-A", "desc": "≥ 300", "unit": "mV"},
            {"color": "#9ACD32", "label": "Conformed with WQG for Class B", "desc": "250–299", "unit": "mV"},
            {"color": "#FFEB3B", "label": "Conformed with WQG for Class C", "desc": "200–249", "unit": "mV"},
            {"color": "#FF9800", "label": "Conformed with WQG for Class D", "desc": "150–199", "unit": "mV"},
            {"color": "#F44336", "label": "Failed the WQG for Classes AA to D", "desc": "< 150", "unit": "mV"},
            {"color": "black", "label": "No Data", "desc": "", "unit": "mV"},
        ],
        "BOD": [
            {"color": "#2196F3", "label": "Conformed with WQG for Class AA", "desc": "≤ 3", "unit": "mg/L"},
            {"color": "#4CAF50", "label": "Conformed with WQG for Class A", "desc": "> 3–5", "unit": "mg/L"},
            {"color": "#9ACD32", "label": "Conformed with WQG for Class B", "desc": "> 5–7", "unit": "mg/L"},
            {"color": "#FFEB3B", "label": "Conformed with WQG for Class C", "desc": "> 7–10", "unit": "mg/L"},
            {"color": "#FF9800", "label": "Conformed with WQG for Class D", "desc": "> 10–15", "unit": "mg/L"},
            {"color": "#F44336", "label": "Failed the WQG for Classes AA to D", "desc": "> 15", "unit": "mg/L"},
            {"color": "black", "label": "No Data", "desc": "", "unit": "mg/L"},
        ],
        "Ammonia": [
            {"color": "#4CAF50", "label": "Conformed with WQG for Classes AA-C", "desc": "≤ 0.06", "unit": "mg/L"},
            {"color": "#FF9800", "label": "Conformed with WQG for Class D", "desc": "> 0.06–0.30", "unit": "mg/L"},
            {"color": "#F44336", "label": "Failed the WQG for Classes AA to D", "desc": "> 0.30", "unit": "mg/L"},
            {"color": "black", "label": "No Data", "desc": "", "unit": "mg/L"},
        ],
        "Nitrate": [
            {"color": "#4CAF50", "label": "Conformed with WQG for Classes AA-C", "desc": "≤ 7", "unit": "mg/L"},
            {"color": "#FF9800", "label": "Conformed with WQG for Class D", "desc": "> 7–15", "unit": "mg/L"},
            {"color": "#F44336", "label": "Failed the WQG for Classes AA to D", "desc": "> 15", "unit": "mg/L"},
            {"color": "black", "label": "No Data", "desc": "", "unit": "mg/L"},
        ],
        "Inorganic Phosphate": [
            {"color": "#4CAF50", "label": "Conformed with WQG for Classes AA-C", "desc": "≤ 0.025", "unit": "mg/L"},
            {"color": "#FF9800", "label": "Conformed with WQG for Class D", "desc": "> 0.025–0.5", "unit": "mg/L"},
            {"color": "#F44336", "label": "Failed the WQG for Classes AA to D", "desc": "> 0.5", "unit": "mg/L"},
            {"color": "black", "label": "No Data", "desc": "", "unit": "mg/L"},
        ],
        "Fecal Coliform": [
            {"color": "#2196F3", "label": "Conformed with WQG for Class AA", "desc": "≤ 20", "unit": "MPN/100mL"},
            {"color": "#4CAF50", "label": "Conformed with WQG for Class A", "desc": "> 20–50", "unit": "MPN/100mL"},
            {"color": "#9ACD32", "label": "Conformed with WQG for Class B", "desc": "> 50–100", "unit": "MPN/100mL"},
            {"color": "#FFEB3B", "label": "Conformed with WQG for Class C", "desc": "> 100–200", "unit": "MPN/100mL"},
            {"color": "#FF9800", "label": "Conformed with WQG for Class D", "desc": "> 200–400", "unit": "MPN/100mL"},
            {"color": "#F44336", "label": "Failed the WQG for Classes AA to D", "desc": "> 400", "unit": "MPN/100mL"},
            {"color": "black", "label": "No Data", "desc": "", "unit": "MPN/100mL"},
        ],
    }